apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm01-pvc-0
  namespace: argocd-test
  labels:
    vm-selector: vm01
  annotations:
    csi.vsphere.volume-requested-topology: '[{"topology.kubernetes.io/zone":"mgmt-01-zone-01"}]'
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: vc-vcf9-mgmt-cl01-vsan-storage-policy
